#!/bin/bash


# Color definitions
NC='\033[0m'
WHITE="\033[1;37m"
GREEN="\033[0;32m"
LIGHT_GREEN="\033[1;32m"
CYAN="\033[0;36m"
GRAY="\033[0;37m"
BLUE="\033[0;34m"
LIGHT_BLUE="\033[1;34m"
YELLOW="\033[1;33m"
RED="\033[1;31m"


BINDIR=$HOME/bin
DOTFILES=$HOME/Dropbox/dotfiles

printf "${LIGHT_GREEN}Dotfiles home: ${NC}${DOTFILES}\n\n\n"


# Setup bash aliases, profiles, etc
printf "${LIGHT_GREEN}Setting up bash aliases, profiles\n\n\n{$NC}"

mkdir $BINDIR
ln -s $DOTFILES/new_sbt $BINDIR/new_sbt


rm -f $HOME/.bash_profile
ln -s $DOTFILES/bash/.bash_profile $HOME/.bash_profile

rm -f $HOME/.bash_aliases
ln -s $DOTFILES/bash/.bash_aliases $HOME/.bash_aliases


# Set up git
rm -rf $HOME/.gitconfig
ln -s $DOTFILES/git/.gitconfig $HOME/.gitconfig

rm -rf $HOME/.git-completion.bash
ln -s $DOTFILES/git/.git-completion.bash $HOME/.git-completion.bash

# Tmux
sudo apt-get install tmux
rm -f $HOME/.tmux.conf
ln -s $DOTFILES/tmux/.tmux.conf $HOME/.tmux.conf


# Set up VIM
sudo apt-get install vim
rm -f $HOME/.vimrc
ln -s $DOTFILES/vim/.vimrc $HOME/.vimrc

rm -rf $HOME/.vim
ln -s $DOTFILES/vim/.vim $HOME/.vim

# Setup SBT for Scala Project
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
sudo apt-get update
sudo apt-get install sbt

# Install HTOP
sudo apt-get install htop


# Source it all for the current session
source $HOME/.bash_profile
source $HOME/.bash_aliases

# Make
sudo apt-get install make

# Ruby Installer
wget -O ruby-install-0.6.1.tar.gz https://github.com/postmodern/ruby-install/archive/v0.6.1.tar.gz
tar -xzvf ruby-install-0.6.1.tar.gz
cd ruby-install-0.6.1/
sudo make install

# TODO: Chruby

# Ruby : Get the latest MRI ruby
ruby-install ruby

